### ISSUE TITLE
Random directional vector

### ISSUE THREAD

**Issue by brianw0924** [realcrane/BASAR-Black-box-Attack-on-Skeletal-Action-Recognition#2]
Hi, 

In the Random exploration section:

Could you explain why the random directional vector is sampled from R^{z*z}, where z = mn/3?

I guess /3 is because three dimension(x,y,z), but why R is z*z matrix?

and, delta = R - (R^T * d) *d, does it mean that R perform orthogonalization w.r.t d?

Thank you.

**Comment by yunfengdiao** [comment]
Hi brianw0924,

(1) The size of one motion is mn, where m is the number of Dofs in one frame and n is the total frame number. A random directional vector sampled from R^{z*z} is to ensure the generated perturbations keep the same size as the motion.
(2) yes

**Comment by realcrane** [comment]
It looks like the issue has been resolved. I will close it now.
