### ISSUE TITLE
Exception:  @error: Insufficient Model  Model must contain at least 1 variable and 1 equation

### ISSUE THREAD

**Issue by ZhouYuxuanYX** [realcrane/BASAR-Black-box-Attack-on-Skeletal-Action-Recognition#3]
Hi,

thanks for your great work! I received the following error: 
'''
 --------- APM Model Size ------------
 Each time step contains
   Objects      :            0
   Constants    :            0
   Variables    :            0
   Intermediates:            0
   Connections  :            0
   Equations    :            0
   Residuals    :            0
 
 
 @error: Insufficient Model
 Model must contain at least 1 variable and 1 equation
 STOPPING...
'''
when running
'''
python untargeted_attack_op_stgcn_hdm05.py 
'''
under demo directory.

I have checked that it is the first time when op_angle function in tools/optimization.py is called at 250th iteration.

**Comment by yunfengdiao** [comment]
Hi Yuxuan,

It seems that the data being fed to the optimizer is none. You could try to check the data before running the optimizer or choosing another target sample to try again.  I ran the project again and here is my logs at 250th iteration:

Step #249...
	Delta step...
	#1
	Epsilon step...
	#1
Epsilon: 0.01406249962747097
Mean Squared Error: 0.014949054457247257
Calls: 1837
Attack Class: tensor([33], device='cuda:0')
Target Class: tensor([54], device='cuda:0')
Initial Class:tensor([62], device='cuda:0')
Delta: 0.025
n target:: 1
apm 36.57.160.95_gk_model0 <br><pre> ----------------------------------------------------------------
 APMonitor, Version 1.0.1
 APMonitor Optimization Suite
 ----------------------------------------------------------------


 --------- APM Model Size ------------
 Each time step contains
   Objects      :            0
   Constants    :            0
   Variables    :         4680
   Intermediates:            0
   Connections  :            0
   Equations    :          118
   Residuals    :          118

 Number of state variables:           4680
 Number of total equations: -            0
 Number of slack variables: -            0
 ---------------------------------------
 Degrees of freedom       :           4680

 Number of bound variables: -         1260

 **********************************************
 Steady State Optimization with Interior Point Solver
 **********************************************


 Info: Exact Hessian

******************************************************************************
This program contains Ipopt, a library for large-scale nonlinear optimization.
 Ipopt is released as open source code under the Eclipse Public License (EPL).
         For more information visit http://projects.coin-or.org/Ipopt
******************************************************************************

This is Ipopt version 3.12.10, running with linear solver ma57.

Number of nonzeros in equality constraint Jacobian...:        0
Number of nonzeros in inequality constraint Jacobian.:        0
Number of nonzeros in Lagrangian Hessian.............:    10089

Total number of variables............................:     3420
                     variables with only lower bounds:        0
                variables with lower and upper bounds:     3420
                     variables with only upper bounds:        0
Total number of equality constraints.................:        0
Total number of inequality constraints...............:        0
        inequality constraints with only lower bounds:        0
   inequality constraints with lower and upper bounds:        0
        inequality constraints with only upper bounds:        0

iter    objective    inf_pr   inf_du lg(mu)  ||d||  lg(rg) alpha_du alpha_pr  ls
   0  1.9122993e+02 0.00e+00 1.00e+02   0.0 0.00e+00    -  0.00e+00 0.00e+00   0
   1  9.1584277e+01 0.00e+00 4.08e-01  -0.3 3.88e-01    -  9.91e-01 1.00e+00f  1
   2  6.9546401e+01 0.00e+00 3.31e-01  -1.6 2.42e-01    -  9.91e-01 1.00e+00f  1
   3  6.8886528e+01 0.00e+00 5.85e-02  -3.6 6.09e-02    -  9.94e-01 1.00e+00f  1
   4  6.8885648e+01 0.00e+00 3.27e-03  -4.7 3.34e-03    -  9.96e-01 1.00e+00f  1
   5  6.8885648e+01 0.00e+00 1.55e-05  -6.8 2.16e-05    -  9.99e-01 1.00e+00f  1
   6  6.8885648e+01 0.00e+00 4.76e-11 -11.0 9.84e-08    -  1.00e+00 1.00e+00f  1

Number of Iterations....: 6

                                   (scaled)                 (unscaled)
Objective...............:   1.5767898370401687e+01    6.8885647600003352e+01
Dual infeasibility......:   4.7603821536901459e-11    2.0796811330037166e-10
Constraint violation....:   0.0000000000000000e+00    0.0000000000000000e+00
Complementarity.........:   1.0059017671775902e-11    4.3945104811232291e-11
Overall NLP error.......:   4.7603821536901459e-11    2.0796811330037166e-10


Number of objective function evaluations             = 7
Number of objective gradient evaluations             = 7
Number of equality constraint evaluations            = 0
Number of inequality constraint evaluations          = 0
Number of equality constraint Jacobian evaluations   = 0
Number of inequality constraint Jacobian evaluations = 0
Number of Lagrangian Hessian evaluations             = 6
Total CPU secs in IPOPT (w/o function evaluations)   =      0.060
Total CPU secs in NLP function evaluations           =      0.467

EXIT: Optimal Solution Found.

 The solution was found.

 The final value of the objective function is    68.8856476000034

 ---------------------------------------------------
 Solver         :  IPOPT (v3.12)
 Solution time  :   0.888299999998708      sec
 Objective      :    68.8856476000034
 Successful solution
 ---------------------------------------------------

Mean Squared Error: 0.01346602477133274
Opt Class: tensor([33], device='cuda:0')
Step #250...
	Delta step...
	#1
	Epsilon step...
	#1
	#2
	#3
Epsilon: 0.007031249813735485
Mean Squared Error: 0.013374005444347858
Calls: 1846
Attack Class: tensor([33], device='cuda:0')
Target Class: tensor([54], device='cuda:0')
Initial Class:tensor([62], device='cuda:0')
Delta: 0.02777777777777778
n target:: 1
